port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 50200
  use_external_ip: true # Важно для локальной разработки

redis:
  address: localhost:6379 # Если используется network_mode: host
  # address: redis:6379 # Если используется стандартная сеть Docker (на Windows/Mac)

keys:
  # DEV KEY (Никогда не используйте это в проде!)
  devkey: secret