global:
  scrape_interval: 5s     # Как часто собирать метрики (для дева часто, для прода 15-60s)
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'kitsulan-core'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8092']